solution: solution.cpp stub-comisie.cpp
	g++ $(CPPFLAGS) stub-comisie.cpp solution.cpp -o solution

ruxandra: ruxandra.cpp stub-comisie.cpp
	g++ $(CPPFLAGS) stub-comisie.cpp ruxandra.cpp -o ruxandra

george: george.cpp stub-comisie.cpp
	g++ $(CPPFLAGS) stub-comisie.cpp george.cpp -o george
